spring:
  application:
    name: pos-system

  datasource:
    url: jdbc:mysql://localhost:3306/possystem
    username: root
    password: Teja@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    generate-ddl: false

  sql:
    init:
      mode: never

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

  endpoint:
    prometheus:
      enabled: true
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8090/eureka/